version: "3.9"

services:
  users-service:
    container_name: users-service
    image: mondocinema/users-service:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    networks:
      - mondocinema

networks:
  mondocinema:
    external: true
